printWidth: 100
bracketSpacing: false
quoteProps: consistent
# デフォルトだけど明示してるだけのやつら↓
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
trailingComma: es5
arrowParens: always
vueIndentScriptAndStyle: false
endOfLine: lf
